import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from '../Provider'
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    // <ChakraProvider>
      <html lang="en">
        <body >
          <Providers>
            <Header/>
            {children}
          </Providers>
        </body>
      </html>
    // </ChakraProvider>
  );
}
